namespace Prome.Viaticos.Server.Domain.Enums
{
    public enum ConceptEnum
    {
        Alojamiento_Beneficios = 1,
        Guardería_Beneficios = 2,
        Refrigerio_Beneficios = 3,
        Estacionamiento_Beneficios = 4,
        BeneficioFit_Beneficios = 5,
        Almuerzo_Beneficios = 6,
        Cena_Beneficios = 7,
        Peaje_Capacitacion = 8,
        Estacionamiento_Capacitacion = 9,
        Almuerzo_Capacitacion = 10,
        Cena_Capacitacion = 11,
        Auto_Capacitacion = 12,
        Moto_Capacitacion = 13,
        TaxiRemis_Capacitacion = 14,
        TransportePublico_Capacitacion = 15,
        Peaje_Terreno = 16,
        Estacionamiento_Terreno = 17,
        Auto_Terreno = 18,
        Moto_Terreno = 19,
        TaxiRemis_Terreno = 20,
        TransportePublico_Terreno = 21,
        Peaje_OtrasReuniones = 22,
        Estacionamiento_OtrasReuniones = 23,
        Auto_OtrasReuniones = 24,
        Moto_OtrasReuniones = 25,
        TaxiRemis_OtrasReuniones = 26,
        TransportePublico_OtrasReuniones = 27,
        Peaje_Cobranza = 28,
        Estacionamiento_Cobranza = 29,
        Auto_Cobranza = 30,
        Moto_Cobranza = 31,
        TaxiRemis_Cobranza = 32,
        TransportePublico_Cobranza = 33,
        Peaje_ReunionMensual = 34,
        Estacionamiento_ReunionMensual = 35,
        Auto_ReunionMensual = 36,
        Moto_ReunionMensual = 37,
        TaxiRemis_ReunionMensual = 38,
        TransportePublico_ReunionMensual = 39,
        Peaje_TraspasoCartera = 40,
        Estacionamiento_TraspasoCartera = 41,
        Auto_TraspasoCartera = 42,
        Moto_TraspasoCartera = 43,
        TaxiRemis_TraspasoCartera = 44,
        TransportePublico_TraspasoCartera = 45,
        Peaje_VisitaSucursal = 46,
        Estacionamiento_VisitaSucursal = 47,
        Auto_VisitaSucursal = 48,
        Moto_VisitaSucursal = 49,
        TaxiRemis_VisitaSucursal = 50,
        TransportePublico_VisitaSucursal = 51,
        Peaje_VisitaCampania = 52,
        Estacionamiento_VisitaCampania = 53,
        Auto_VisitaCampania = 54,
        Moto_VisitaCampania = 55,
        TaxiRemis_VisitaCampania = 56,
        TransportePublico_VisitaCampania = 57,


    }
}
